### ISSUE TITLE
Questions about spatial resolution of UBERON ontologies

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ontology#48] opened 2019-10-15 12:46 UTC
As a data wrangler for the WSSS projects I need to try to match the spatial organ terms they are using with suitable ontology organ and organ part ontologies. There are a few organs where there are gaps in specific spatial ontologies and I want to understand if these are terms that could/should be added to UBERON, or if we need to look in to using an alternate ontology, e.g. [Biological Spatial Ontology](https://www.ebi.ac.uk/ols/ontologies/bspo) to get a more specific definition of the spatial area the specimen was taken from. Some examples I have so far are:

**Kidney**
- Upper pole
- Lower pole
![kidney_anatomogram](https://user-images.githubusercontent.com/13007987/66826659-e462b700-ef44-11e9-9b7d-beeee0ef316f.png)

**Uterus**
- Lower section
- Mid section
- Upper section
![female_reproductive](https://user-images.githubusercontent.com/13007987/66826711-00feef00-ef45-11e9-9dc4-e9d3d4c2c8d1.png)

**Small Intestine**
- Subsections of jejunum
- terminal ileum
- second part of duodenum
![small_intestine](https://user-images.githubusercontent.com/13007987/66826757-24c23500-ef45-11e9-9cd4-37a057d64be9.png)
**Skeletal muscle**
- Intercostal muscle between rib 2 and 3

**Bone**
- Head/distal end
![bone](https://user-images.githubusercontent.com/13007987/66826822-47ece480-ef45-11e9-89f6-6f9eb3987db0.png)

**Liver**
- Surface central region
- Surface cranial region
- Deep parenchymal central region (towards hilum)
![Liver](https://user-images.githubusercontent.com/13007987/66832521-fdbe3000-ef51-11e9-9b70-19028d297173.png)

We have also had feedback from CBTM who think that they need more fine grained terms to accurately capture some of the samples they are collecting from organs.

**Comment by mshadbolt** [comment] 2019-11-07 13:37
@zoe @simonjupp was just wondering if you have any thoughts about how to get better spatial resolution when defining where specimens are being taken from within organs.

**Comment by simonjupp** [comment] 2019-11-07 16:01
If we can standardise to a common model on the `spatial index`, then we should look to add this as a new property in the metadata schema so users can provide alongside the uberon term for the primary biopsy site name. 

For the specific biopsy site, many of these should already be covered by Uberon/FMA (https://www.ebi.ac.uk/ols/ontologies/fma). It would be good to get a list of the ones you've encountered that didn't map to anything.

**Comment by mshadbolt** [comment] 2019-11-11 01:51
See the first post of the ticket for a list of organ parts that don't map to terms in the uberon ontology. We don't use the FMA ontology.

**Comment by mshadbolt** [comment] 2019-12-09 11:29
@simonjupp do you think we should add the FMA ontology to our schema to allow a wider variety of anatomy terms to be used for organ parts?

**Comment by simonjupp** [comment] 2019-12-10 11:04
We can import from FMA. These will end up as subclasses of uberon terms in the HCAO so it won't effect validation. Just let @zoependlington know the list of FMA terms you want.

**Comment by mshadbolt** [comment] 2019-12-17 09:30
I made a ticket (#54) to add some terms from the FMA as children of organ terms in UBERON in our HCAO

**Comment by paolaroncaglia** [comment] 2020-10-22 16:25
Hi @mshadbolt,
 
> I made a ticket (#54) to add some terms from the FMA as children of organ terms in UBERON in our HCAO

Any objection if I close this ticket as a duplicate of #54? 
I will then look into #54 and address any missing task (I see that Zoë has already done some work).

Thanks,
Paola

**Comment by mshadbolt** [comment] 2020-10-22 16:26
ok sounds good

**Closed** 2020-10-22 16:36 UTC
