### ISSUE TITLE
GSE107746

### ISSUE THREAD

**Issue by Asgton** [HumanCellAtlas/ontology#64] opened 2020-09-16 16:19 UTC
collection_protocol_4

ontology for 'hydrolisis' collection protocol

At last, we removed zona pellucida of oocytes by hydrolysis with 0.012 M hydrochloric acid to obtain naked oocyte without contamination of GCs

**Comment by Asgton** [comment] 2020-09-22 21:19
organ part ontology id for preovulatory follicle

**Comment by paolaroncaglia** [comment] 2020-10-30 15:53
Hi @Asgton ,
I'm new to this project, I'll be helping with HCA ontology requests. Do I understand correctly that you are looking for a term to represent the hydrolysis protocol above? If so I'll create one in EFO in the 'protocol' branch. 
Do you also need a term for preovulatory follicle? If so, would the existing Uberon term [UBERON:0003982 'mature ovarian follicle'](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0003982) fit your need? (It has a related synonym of "preovulatory follicle".) 
Thanks,
Paola

**Comment by paolaroncaglia** [comment] 2020-11-05 14:25
Hi @pnejad and @mshadbolt ,

May I please ask for your advice on this ticket - would you agree with my proposed strategy above?

Many thanks,
Paola

**Comment by pnejad** [comment] 2020-11-10 21:17
@paolaroncaglia Sorry for the delayed response. Asgton is a former team member who has since moved on. Your proposed plan works great:

- hydrolysis to be added to EFO's protocol step
- UBERON:0003982 to be used for preovulatory follicle

Could you please tag me in the EFO ticket for hydrolysis so I can follow when it is released?

**Comment by paolaroncaglia** [comment] 2020-11-12 15:50
@pnejad 

> @paolaroncaglia Sorry for the delayed response. Asgton is a former team member who has since moved on. Your proposed plan works great:
> 
>     * hydrolysis to be added to EFO's protocol step
> 
>     * UBERON:0003982 to be used for preovulatory follicle
> 
> 
> Could you please tag me in the EFO ticket for hydrolysis so I can follow when it is released?

Sure, the ticket is https://github.com/EBISPOT/efo/issues/891 and I tagged you there. Thanks.

**Comment by pnejad** [comment] 2021-04-20 20:29
@paolaroncaglia  Hydrolysis is not being recognized by HCAO, is this something that will be resolved after the developers release the new version of HCAO?

**Comment by paolaroncaglia** [comment] 2021-04-21 08:41
Hi @pnejad ,

> @paolaroncaglia Hydrolysis is not being recognized by HCAO, is this something that will be resolved after the developers release the new version of HCAO?

The term EFO_0010892 'hydrolisis collection protocol' is in the HCA OLS production instance, see [here](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010892) please. A typo sneaked in (hydrolisis for hydrolysis) for which I apologize; possibly that's why you couldn't find the term? I noticed the typo yesterday and it will be surely fixed in time for the next HCAO release (ticket [here](https://github.com/EBISPOT/efo/issues/1065)). Please let me know if EFO_0010892 is not available to you, that'd be a broader issue than the typo to look into.

Thanks,
Paola

**Comment by pnejad** [comment] 2021-04-21 17:14
Hi @paolaroncaglia, we tested the submission of our dataset with the incorrect spelling to see if there are any issues with EFO_0010892, and ingest is still giving us an error.

**Comment by paolaroncaglia** [comment] 2021-04-22 14:09
Hi @pnejad ,

> Hi @paolaroncaglia, we tested the submission of our dataset with the incorrect spelling to see if there are any issues with EFO_0010892, and ingest is still giving us an error.

Is the ingest still failing with the new release that @zoependlington just made today, see https://github.com/ebi-ait/hca-ebi-dev-team/issues/409? If yes, could you please provide more details, e.g. error log? 

Thank you, I'm not sure what the problem is but we'll address it as promptly as we can.

Paola

**Comment by paolaroncaglia** [comment] 2021-05-13 07:02
Note for self: I'm closing this ticket as it was resolved elsewhere (see https://github.com/ebi-ait/hca-ebi-dev-team/issues/409#issuecomment-827672324 and following comments in that ticket).

**Closed by paolaroncaglia** 2021-05-13 07:02 UTC
